import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  const { word, source, target } = await req.json();

  // Combined mock dictionary – Tamil script + Romanized Tamil
  const mock: Record<string, string> = {
    // === Unicode Tamil (script) ===
    'ஹாய்': 'Hi',
    'ரியா': 'Riya',
    'பள்ளி': 'school',
    'எப்படி': 'how',
    'இருந்தது': 'was',
    'இன்று': 'today',
    'மிகவும்': 'very',
    'வேடிக்கையாக': 'fun',
    'நீ': 'you',
    'என்ன': 'what',
    'கற்றாய்': 'learned',
    'நாம்': 'we',
    'புதிய': 'new',
    'கணித': 'math',
    'முறைகள்': 'methods',
    'கற்றோם': 'learned',
    'கணிதம்': 'mathematics',
    'கொஞ்சம்': 'a little',
    'கடினமாக': 'hard',
    'தெரிகிறது': 'seems',
    'இல்லை': 'no',
    'ஆசிரியர்': 'teacher',
    'அதை': 'it',
    'எளிதாக': 'easily',
    'செய்தார்': 'made/did',
    'அது': 'that',
    'நன்றாக': 'well',
    'இருக்கிறது': 'is',
    'ஆம்': 'yes',
    'நான்': 'I',
    'வகுப்பை': 'class',
    'ரசித்தேன்': 'enjoyed',
    'உனக்கு': 'to you',
    'அறிவியல்': 'science',
    'வகுப்பு': 'class',
    'இருந்ததா': 'was there?',
    'ஒரு': 'a/one',
    'சோதனை': 'experiment',
    'செய்தோம்': 'we did',
    'வாவ்': 'wow',
    'நிறங்களையும்': 'colors also',
    'தண்ணீரையும்': 'water also',
    'கலந்தோம்': 'we mixed',
    'அருமையாக': 'awesome',
    'ஆங்கில': 'English',
    'சிறிய': 'small',
    'கதையை': 'story',
    'படித்தோம்': 'we read',
    'அந்த': 'that',
    'கதை': 'story',
    'பிடித்ததா': 'liked?',
    'சுவாரஸ்யமாக': 'interesting',
    'போல': 'seems like',
    'விரும்பினேன்': 'liked',
    'தமிழ்': 'Tamil',

    // === Romanized Tamil (from conversation sentences) ===
    'Haai': 'Hi',
    'Riya': 'Riya',
    'palli': 'school',
    'eppadi': 'how',
    'irundhathu': 'was',
    'Indru': 'today',
    'migavum': 'very',
    'vedikkaiyaaga': 'fun',
    'Nee': 'you',
    'enna': 'what',
    'katraai': 'learned',
    'Naam': 'we',
    'pudhiya': 'new',
    'kanitha': 'math',
    'muraigal': 'methods',
    'katrom': 'learned',
    'Kanitham': 'mathematics',
    'konjam': 'a little',
    'kadinamaaga': 'hard',
    'therigiradhu': 'seems',
    'Illai': 'no',
    'aasiriyar': 'teacher',
    'athai': 'it',
    'elidhaaga': 'easily',
    'seithaar': 'made',
    'Adhu': 'that',
    'nandraga': 'well',
    'irukiradhu': 'is',
    'Aam': 'yes',
    'vaguppai': 'class',
    'rasithen': 'enjoyed',
    'Unakku': 'to you',
    'ariviyal': 'science',
    'irundhadha': 'was there?',
    'oru': 'a',
    'sothanai': 'experiment',
    'seithom': 'we did',
    'Vaav': 'wow',
    'nirangalaiyum': 'colors also',
    'thanneeraiyum': 'water also',
    'kalandhom': 'we mixed',
    'arumaiyaaga': 'awesome',
    'Aangila': 'English',
    'siriya': 'small',
    'kathaiyai': 'story',
    'padithom': 'we read',
    'andha': 'that',
    'kathai': 'story',
    'pidithadha': 'liked?',
    'suvaarsiyamaaga': 'interesting',
    'pola': 'seems like',
    'virumbinen': 'liked',
  };

  const translation = mock[word] || word;
  return NextResponse.json({ translation });
}